# Generated by Django 5.1.7 on 2025-04-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_end_date_product_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddingproduct',
            name='is_auto_bid',
            field=models.BooleanField(default=False),
        ),
    ]
