# Generated by Django 5.1.7 on 2025-04-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_biddingproduct_is_auto_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddingproduct',
            name='is_win',
            field=models.BooleanField(default=False),
        ),
    ]
